### ISSUE TITLE
:busts_in_silhouette: Fill-in missing Speaker profile images

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2019.djangocon.us#112]
Check out the [_presenters](https://github.com/djangocon/2019.djangocon.us/tree/master/_presenters) folder and most of our Presenters don't have profile photos yet.  

The profile images go in the `photo_url` field. This may be either a `url` starting with `https://` or it can be a file which is uploaded to the `/static/img/speakers/` folder. If the presenter is an organizer, the may already have an image in the `/static/img/organizers/` folder. (we could merge these into one folder which might make a better v2 feature.)

We have all but three:

- [x] Cara Borenstein
- [x] Blythe Dunham
- [x] Mike Hansen

**Comment by KatherineMichel** [comment]
We have the photos now for the people listed above. I have reached out to Jeffrey Eliasen via Twitter to see if he wants to provide photo or other presenter info.

**Comment by jefftriplett** [comment]
I'm going to close this but a pull request to get Jeffrey's would be great.
