### ISSUE TITLE
Blog Post+Listing Improvements

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2019.djangocon.us#13]
The blog needs to be more visual:

* [x] Better support for wider imagery
* [x] Make it easier to introduce and layout icons - Handled in the styleguide with Media Objects
* [x] Reassess coloring and spacing of headings
* ~~[ ] Consider a header photo for the blog listing~~ - Tried this, it didn't work. Competed too much with the content.
* ~~[x] Default blog image~~ - Existed or add via existing patterns
* ~~[x] Per post images~~ - Existed

**Comment by mtrythall** [comment]
@williln you had some thoughts here. Care to add?

@jonitrythall You too

Feel free to ping anyone else. I started with the basics.

**Comment by williln** [comment]
My thoughts were basically around the social media image sharing. Last year we used the `image` metadata item to add an image that would display in the article preview on Twitter, FB, etc. 

`image: /static/img/blog/fin_aid_allocation.png`, for example. 

But most of the blog posts themselves didn't have images. It would be nice to possibly: 

- have a default header image for each blog post 
- be able to add our own header images to blog posts to customize them 
- Have an easy way to add the logo and text to images for social sharing in a consistent way. We used Pablo last year, which was fine, but we are limited in the fonts we have access to with Pablo

**Comment by mtrythall** [comment]
Cool, thanks @williln. First two bullets are straightforward. I've added them to the improvements above.

Is Pablo some software you're using to adjust images? Can you tell me more about your last bullet please?

**Comment by williln** [comment]
@mtrythall Sure! [Pablo](https://pablo.buffer.com/) is an online tool that lets you upload images/logos and add text to them, then download the completed image for posting on the web. It's how we made the images in tweets like [this one](https://twitter.com/djangocon/status/1031839073038741505).  

Pablo's limitation is that it only gives us a few fonts and I'm petty sure it only allows for one "logo" (so no uploading the djangocon logo AND ALSO the little crab or boat or something). It doesn't make sense to ask you to recreate Pablo. But a couple of templates that were editable in Gimp or Photoshop or equivalent (or editable SVGs but I know truly nothing about SVG) for things like these announcements, speaker "cards", would be nice. If this is out of scope that makes sense, and we already have a solution in Pablo that's been working pretty well for us.

**Comment by mtrythall** [comment]
You can now use `post_photo_url` and `post_photo_alt` to add a photo at the beginning of the content.

If you add `post-photo` to the class on a photo, it will extend out past the width of the content and appear larger. Not full width since that adds some crazy complications, but a bit larger to stand out.
