### ISSUE TITLE
:arrow_up: Update Orientation details and schedule

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2019.djangocon.us#146]
@williln spotted this https://github.com/djangocon/2019.djangocon.us/pull/145/files/95e08f469e4bddccf0ae55267ab217012ac88512

which is a good reminder that we need to roll a 2019 update.

**Comment by kojoidrissa** [comment]
@jefftriplett good catch by @williln. I've been gathering thoughts on this. I'll put them in a Markdown file on my way back from PyConLatam.

**Comment by kojoidrissa** [comment]
Pull request at #155
