### ISSUE TITLE
Website Updates

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2019.djangocon.us#18]
Some updates to be made/verified for 2019. Schedule pages not included.

## DONE! ~Community~

- [x] Update README.md with current guidance (Kati's PR was merged for develop branch updates)
- [x] Updating CONTRIBUTING with current guidance

## Styleguide

- [ ] Styleguide- Michael is working on this; input would be helpful about what contributors need assistance with
- [x] Make sure style guide reference to Financial Aid has been updated to Opportunity Grants

## Throughout Website (including Footer)

- [ ] Verify content updates are inline with Michael's CSS changes (ex. buttons from 2018)
- [x] New favicon
- [ ] Verify that site email/link variables are used instead of hard-coding and that they work
- [x] Add nursing/private room info (not sure where this goes; are nursing room and quiet room separate rooms?) - separate Trello card, will address later 
- [x] Update speaking policy/timeline, if needed
- [ ] Update compensation policy in particular, if needed (see Speaking page- Tutorials section, could be other places as well)
- [x] Go through commented out content and make sure nothing missed to be added back (see also 2018 website list for some info about things commented out)
- [x] Check with local organizers to see if they think anything should be changed/added -- Calling this good for now (Lacey) 
- [x] Update ticket price policy/timeline, if needed
- [x] Update refund policy/timeline, if needed
- [x] Update financial aid policy/timeline, if needed (per Deatz, “Financial Aid” will become “Opportunity Grant”)
- [x] Update sponsor policy/timeline, if needed
- [x] Update hotel policy/timeline, if needed
- [x] Will email addresses remain the same? (hello@djangocon.us, conduct@djangocon.us, sponsors@djangocon.us, visas@djangocon.us)
- [x] Change financialaid@djangocon.us/opportunitygrants@djangocon.us to grants@djangocon.us
- [x] Remove old files such as blog posts, menu if outdated, etc.
- [x] Fix Buy Tickets link in navbar
- [x] Room Sharing links needs to be commented out at the bottom of the Venue navbar or updated before launch (presumably there is a commented out section in venue file)
- [x] Link to 2019 Colophon page in footer? Updates? (includes sponsors)
- [x] Social media icons in footer should open to pages with updated branding (outside website scope, but noticeable)
- [x] Copyright date change to 2019 (has been done in landing page)
- [x] There is some disparity between title and non-title case for page names, policy names (speaking page versus Speaking page, code of conduct versus Code of Conduct) that would be nice to make consistent across the site.

## Homepage

- [ ] Update/verify conference day descriptions (possible change in tracks)
- [x] Update sponsors, as needed (also, some might return)
- [x] Verify Code of Conduct page, Financial Aid page links opens to corresponding 2019 website page (not GitHub page)
- [x] Update conference dates
- [x] Reset card info, including State of Django card to something else
- [x] Update Buy Tickets and Submit Talk links (up-to-date, _config.yml variables need to be uncommented, when ready)
- [x] Comment out Schedule page link
- [x] Will Join mailing list link remain the same?
- [x] Had Join mailing list link on landing page; add to homepage for launch? (switched CFP button to mailing list button bc/cfp might not be available at launch)
- [x] Replace blog post cards with new post(s)

Note: per Deatz, this link will probably be added closer to conference
- [x] Add a Be a Volunteer sign up link? (last year, was replaced with Speaking page link) -- Created separate Trello card, will be done closer to conference 

## About

- [ ] Update/verify conference day descriptions (possible change in tracks)
- [x] Verify Code of Conduct page, Financial Aid page link opens to corresponding 2019 website page
- [x] Update conference dates
- [x] Update Commitment to Diversity card year
- [x] Update CFP and Opportunity Grant links
- [x] Day 1 Orientation- assuming this is happening again (Yes it is - deatz). 
- [x] Day 1 Orientation- "More details coming in the blog." (per Kojo, content is ok for now, might make some updates in the future)
- [x] Fix Code of Conduct page link that is redirecting from coc

## DONE! ~Tickets~

- [x]  is Patron Ticket holder "special "thank you" event at the conference" happening? (Deatz asked Jeff)
- [x] Ticket policy/timeline correct?  (per Deatz, pricing will stay the same)
- [x] Refund policy/timeline correct? (change cutoff to AoE?)
- [x] Reset content- "Tickets are nearly sold out!" box and "DjangoCon US has sold out the past two years, so buy your ticket soon!"
- [x] Update with 2019 Buy Tickets link
- [x] Comment out/update Waiting List link
- [x] Fix typo "shoud" to "should", if text re-used
- [x] Not sure if DjangoCon US sold out last two years- update, if needed (for simplicity sake, updated to be last year)

## DONE! ~FAQs~

- [x] Update with 2019 Slack channel link in Schedule section (link was deleted in 2018; see _config.yml) -- Created Trello card, will do closer to conference 
- [x] Verify Tickets, Speaker Resources, Venue, Opportunity Grant, and Become a Sponsor page links open to corresponding 2019 website pages
- [x] Ticket section info correct?  (per Deatz, pricing will stay the same)
- [x] Schedule section info correct?
- [x] Speaking section info correct? (per Deatz, this is ok)
- [x] Refund section info correct?
- [x] Commented out board game night text
- [x] Update tickets link (1 instance in Tickets section, could be more commented out?)
- [x] Comment out Schedule page link in Schedule section
- [x] Reset content, in particular reference to 2018 and being "sold out"
- [x] Reset Sponsors section text, removing reference to 2018
- [x] Will childcare reimbursement happen again?  (see also Venue page) (yes - deatz)
- [x] Will have broken blog post link for child care in Accessibility section (commented out link)
- [x] Accessibility section info correct? (probably, but would be good to double check what is listed; per hotel rep, accessibility offerings have not changed)

## DONE! ~CoC~

- [x] Make sure that we have covered everything relevant in Important Numbers section (there was a contact option noted last time that wasn't used- double check?)
- [x] Verify Conference Code of Conduct page link opens corresponding 2019 website page
- [x] Verify that all info in Important Numbers section is still accurate
- [x] Is phone number still accurate in Need help? box (not sure yet, commenting out for now)
- [x] Is conduct@djangocon.us email still accurate in Need help? box (per Deatz, yes)
- [x] Change 2018 to 2019 in Photography section

## DONE! ~Financial Aid (RENAME: Opportunity Grants)~

- [x] Add text calling out terminology change (can ping a Chair or the Comm team for this; Katia is working on this)
- [x] Verify Become a Sponsor page links (2 links) open to corresponding 2019 website page
- [x] Per Deatz, “Financial Aid” will become “Opportunity Grant”
- [x] Opportunity grants policy correct? (per Deatz, this is not changing)
- [x] Changed page name to Opportunity Grants
- [x] Reset text, including changing/removing "Our [Opportunity Grants] application is now closed and all decision notifications have been sent."
- [x] Fix site.opportunity_grants_email (not rendering properly)
- [x] Rename id="financial-aid" still in use (fixed by Lacey)

Note: There is some commented out info removed in 2018 that might need to be added back in: https://raw.githubusercontent.com/djangocon/2018.djangocon.us/d7b942126813ec7beccb5bc679d479db834389eb/_pages/financial-aid.md

## DONE! ~Why DjangoCon US?~

- [x] Update popular sessions/videos links from past years with any 2018 content?; make sure links still work (Deatz will provide)
- [x] Any updates to Additional Topics?
- [x] Remove Talks, Tutorials, Sprints pages links (can add back in future)
- [x] Update "TBD each" with tutorials price  (per Deatz, pricing will stay the same)
- [x] Update with 2019 Buy Tickets link

## DONE! ~Organizers~

- [x] Update organizer cards, as needed, are links still accurate? (Kati reached out to all confirmed organizers not listed to request that they update or give her info if they want to be listed at launch) -- Calling this done; most look to be there now 
- [x] Obtain photos to replace any placeholders
- [x] Make sure reference to Financial Aid has been changed to Opportunity Grants

## DONE! ~Venue~

- [x]  Change rate expiration date (verify correct Book a Room link in _config.yml; hotel rep Allison provided link and expiration date)
- [x]  Double check that favorite spots restaurants and links still accurate; any interest in changing? (can double check with local organizers too) -- Calling this done; we can update closer to time if we want 
- [x] Accessibility section info correct? (probably, but would be good to double check what is listed; see also FAQs page; per hotel rep, accessibility offerings have not changed)
- [x]  Update Book a Room link (up-to-date, _config.yml variables need to be uncommented, when ready)
- [x]  Update group rate
- [x]  Changed "expired" to "expires"
- [x] Will childcare reimbursement happen again? (see also FAQs page) (yes - deatz)
- [x] Will have broken blog post link for child care reimbursement (commented out link)
- [x]  Is Grace still the Marriott rep and phone number still accurate? (commented this out, it was not used when 2018 site went live, apparently just when almost sold out?)
- [x]  Double check Other Hotel Options section info and rates (might be out-of-date now) (commented this out, it was not used when 2018 site went live, apparently just when almost sold out?)
- [x] Any updates to recovery meeting info? Is recovery@pyphilly.org still to be listed? (per Tim, leave this)
- [x] Will the Quiet Room still be Sante Fe 3? (See also Speaking Resources page; Deatz/Cassie verified room will stay the same)

## DONE! ~Room and Ride Sharing~

- [x] Update spreadsheet link (2 places)  

## Speaking at DjangoCon US

- [x] Speaker policy/timeline correct? (per Deatz, program team is double checking this; uncomment mentor info?)
- [ ] Add button to submit talk (link to Papercall CFP) 
- [ ] Add button to submit opportunity grant application (link to Google form) 
- [x] Update CFP/AOE info (commented this out for now, along with speaker mentors link)
- [x] Update Talks, Tutorials, and Lightning Talks heading dates
- [x] Reset content, including "Our Call for Proposals is now closed and all decision notifications have been sent." and "Travel costs are not included, but potential speakers were encouraged apply for financial aid. Financial aid decision notifications have all been sent."
- [x] Will Lightning Talks happen all three talk days? If not, update Lightning Talks heading dates (per Jeff will happen all three days)
- [x] Update talk example links to include 2018
- [x] Fix Why speak at DjangoCon heading
- [x] :zap: emoji in Lightning Talks heading is broken in 2018 site (works in 2019 site)

Note: Add submit a talk/apply for financial aid buttons? https://raw.githubusercontent.com/djangocon/2018.djangocon.us/d7b942126813ec7beccb5bc679d479db834389eb/_pages/speaking.md

## DONE! ~Speaking Resources~

- [x] Update mentor info, as needed, are links still accurate? (per Deatz, comment this section out for launch)
- [x] Will the Speaker Green Room still be Sante Fe 4?(Deatz/Cassie verified room will stay the same)
- [x] Update dates that Speaker Green Room will be open, if needed (Deatz/Cassie verified room is staying the same)
- [x] Will the Quiet Room still be Sante Fe 3? (See also Venue page, Deatz/Cassie verified room will stay the same)

## DONE! ~Our Sponsors~

- [x] Update sponsors, as needed (also, some might return)
- [x] Verify Become a Sponsor for 2019 button link opens corresponding 2019 website page
- [x] Reset Sponsor DjangoCon US box content, removing reference to 2018

## DONE! ~Become a Sponsor~

- [x] Button CSS still correct?
- [x] Update sponsor policy, if needed
- [x] Update Other Sponsorship Opportunities table and info (per Deatz, updated diamond and platinum exhibit table numbers to 2)
- [x] Changed lanyard sponsor price to $2500 (lanyard price went up to $2500 this year - deatz)
- [x] Reset content, removing/updating "Sponsorship is closed for this year." and possibly "Lanyard $2,000 (Limit 1) SOLD!" (Deatz checking on "Sold" status)
- [x] :heavy_check_mark: emoji in table is broken in 2018 site (works in 2019 site)

**Comment by mtrythall** [comment]
So for the emojis, it looks like awhile ago the plugin we're using had an update:

https://github.com/jekyll/jemoji/releases/tag/v0.10.2

^^ I think a fresh install or `bundle update` fixes all of them, at least so for me locally.

**Comment by KatherineMichel** [comment]
@mtrythall They are working for me locally for 2019 site.
