### ISSUE TITLE
Add slides, github, and website links for presenters?

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2019.djangocon.us#214]
Our presentation templates support `slides_url` if someone wants to track them down. 

To add, `github` and `website` link support to presenters, look here: https://raw.githubusercontent.com/djangocon/2019.djangocon.us/master/_presenters/

**Comment by jefftriplett** [comment]
One done: https://2019.djangocon.us/talks/prepping-your-project-for-production/

**Comment by jefftriplett** [comment]
A nice place to find these: https://2019.djangocon.us/speaking/status/

**Comment by KatherineMichel** [comment]
FYI for anyone interested in this issue, many of the slides links are shown in the DjangoCon US videos. I've already found the slides that I could find on Twitter, but there might be more there also.
