### ISSUE TITLE
Fix embed video aspect ratio

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2019.djangocon.us#215]
Our video embed is slightly off and needs the size updated. See here for details: 

https://2019.djangocon.us/talks/prepping-your-project-for-production/

To update the size, this template needs modified: https://github.com/djangocon/2019.djangocon.us/blob/master/_includes/youtube-embed.html

**Comment by safranklin** [comment]
@cedarfall looks like you beat me to the punch in claiming this issue.

I would suggest a more responsive approach covered here: https://jameshfisher.com/2017/08/30/how-do-i-make-a-full-width-iframe/

Forcing iFrame width/height:
![Forcing iframe width and height](https://user-images.githubusercontent.com/37414077/67408290-c4577700-f586-11e9-8a57-8ff06f518deb.png)

"Responsive approach" covered in the article linked above:
![Responsive Approach](https://user-images.githubusercontent.com/37414077/67408346-d507ed00-f586-11e9-9de5-62082def50ff.png)

**Comment by jefftriplett** [comment]
@cedarfall we'd happily accept your pr and thank you @safranklin for going the extra mile to explain how to make it responsive.
